
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue May 13 22:47:27 CDT 2014
//----------------------------------------------------

package Practica3;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 16;
  public static final int PLUS = 14;
  public static final int CLOSE = 4;
  public static final int WHILE = 25;
  public static final int SEMI = 3;
  public static final int array = 21;
  public static final int IF = 23;
  public static final int real_num = 19;
  public static final int MINOR_EQUALS = 12;
  public static final int DO = 26;
  public static final int integer_num = 18;
  public static final int EQUALS = 13;
  public static final int EOF = 0;
  public static final int of = 22;
  public static final int id = 20;
  public static final int DIV = 17;
  public static final int DOTS = 5;
  public static final int MINUS = 15;
  public static final int error = 1;
  public static final int ASSIGN = 2;
  public static final int MINOR_THAN = 10;
  public static final int MAJOR_EQUALS = 11;
  public static final int INTEGER = 7;
  public static final int then = 24;
  public static final int OPEN = 6;
  public static final int REAL = 8;
  public static final int mod = 27;
  public static final int MAJOR_THAN = 9;
}

