
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Apr 16 16:59:31 CDT 2014
//----------------------------------------------------

package Practica3;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PTR = 7;
  public static final int CLOSE = 6;
  public static final int WHILE = 19;
  public static final int SEMI = 3;
  public static final int oprel = 10;
  public static final int array = 15;
  public static final int IF = 17;
  public static final int real_num = 13;
  public static final int DO = 20;
  public static final int integer_num = 12;
  public static final int oparit = 11;
  public static final int EOF = 0;
  public static final int of = 16;
  public static final int id = 14;
  public static final int DOTS = 4;
  public static final int error = 1;
  public static final int ASSIGN = 2;
  public static final int INTEGER = 8;
  public static final int then = 18;
  public static final int OPEN = 5;
  public static final int REAL = 9;
  public static final int mod = 21;
}

