package Practica2;

//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Mar 13 22:00:05 CST 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 10;
  public static final int SIN = 19;
  public static final int PLUS = 8;
  public static final int RPAREN = 4;
  public static final int CLOSE = 14;
  public static final int COS = 20;
  public static final int SEMI = 2;
  public static final int LN = 18;
  public static final int MAG = 17;
  public static final int SQRT = 22;
  public static final int LPAREN = 3;
  public static final int ID = 24;
  public static final int EXP = 12;
  public static final int EQUALS = 6;
  public static final int COMA = 5;
  public static final int NUMBER = 23;
  public static final int EOF = 0;
  public static final int NORM = 16;
  public static final int DIVIDE = 11;
  public static final int PI = 7;
  public static final int MINUS = 9;
  public static final int error = 1;
  public static final int DOT = 15;
  public static final int OPEN = 13;
  public static final int TAN = 21;
}

